package constant

// nolint
const (
	// CONF_CONSUMER_FILE_PATH ...
	CONF_CONSUMER_FILE_PATH = "CONF_CONSUMER_FILE_PATH"
	// CONF_PROVIDER_FILE_PATH ...
	CONF_PROVIDER_FILE_PATH = "CONF_PROVIDER_FILE_PATH"
	// APP_LOG_CONF_FILE ...
	APP_LOG_CONF_FILE = "APP_LOG_CONF_FILE"
	// CONF_ROUTER_FILE_PATH Specify Path variable of router config file
	CONF_ROUTER_FILE_PATH = "CONF_ROUTER_FILE_PATH"
)
